[CmdletBinding()]
param(
    [string]$AccountName = "localstore",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($AccountName -notmatch '^[a-z0-9]{3,24}$') {
    throw "AccountName must be 3-24 lowercase letters and numbers."
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$envPath = Join-Path $repoRoot ".env"

if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
    Write-Host ".env already exists at $envPath"
    Write-Host "Use -Force to replace it with a new Azurite key."
    exit 0
}

$keyBytes = [byte[]]::new(64)
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try {
    $rng.GetBytes($keyBytes)
}
finally {
    $rng.Dispose()
}

$accountKey = [Convert]::ToBase64String($keyBytes)

$content = @(
    "# Generated by scripts/init-local-env.ps1. Do not commit this file."
    "AZURITE_ACCOUNT_NAME=$AccountName"
    "AZURITE_ACCOUNT_KEY=$accountKey"
)

Set-Content -LiteralPath $envPath -Value $content -Encoding ascii

Write-Host "Wrote $envPath"
Write-Host "Run: docker compose up -d --build"
